apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared-ip
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
    - port: 20
      name: ftps-data
      targetPort: 20
      protocol: TCP
    - port: 21
      name: ftps-mgr
      targetPort: 21
      protocol: TCP
    - port: 21000
      name: ftp-passive
      targetPort: 21000
      protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deploy
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_image:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 21000
