apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
    app: ftps
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.102
  selector:
    app: ftps
  ports:
    - port: 20
      name: ftps-data
      targetPort: 20
      protocol: TCP
    - port: 21
      name: ftps-cmd
      targetPort: 21
      protocol: TCP
    - port: 21000
      name: ftp-passive
      targetPort: 21000
      protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deploy
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps_image:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 20
          name: ftps-data
        - containerPort: 21
          name: ftps-cmd
        - containerPort: 21000
          name: ftp-passive
