apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: shared-ip
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
    - port: 5050
      name: wordpress
      targetPort: 5050
      protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deploy
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress_image:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
